//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int id { get; set; }
        public string userId { get; set; }
        public Nullable<double> attendanceHours { get; set; }
        public Nullable<System.DateTime> attendanceDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
