//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string SubjectCode { get; set; }
        public string SemesterCode { get; set; }
        public string DepartmentCode { get; set; }
        public string ClassDay { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Venue { get; set; }
        public bool ClassFlag { get; set; }
        public string StaffID { get; set; }
        public int id { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
