//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Users = new HashSet<User>();
        }
    
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string StaffSurname { get; set; }
        public string StaffEmail { get; set; }
        public string StaffPhone { get; set; }
        public string StaffStreet { get; set; }
        public string StaffCity { get; set; }
        public string StaffPostalCode { get; set; }
        public System.DateTime StaffHireDate { get; set; }
        public string SemesterCode { get; set; }
        public string StaffOffice { get; set; }
        public string StaffDepartmentCode { get; set; }
        public string StaffDesignation { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
