//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidlyMessage
    {
        public int id { get; set; }
        public string creatorID { get; set; }
        public string msgSubject { get; set; }
        public string msgBody { get; set; }
        public Nullable<System.DateTime> msgDate { get; set; }
        public Nullable<int> parentMsgID { get; set; }
    
        public virtual User User { get; set; }
    }
}
